import assert from 'node:assert/strict';
import fs from 'node:fs';
import { JSDOM, VirtualConsole } from 'jsdom';
const errors=[];const console=new VirtualConsole();console.on('jsdomError',e=>errors.push(e.message));
const reports=[{id:'bug-1',kind:'bug',status:'new',name:'Tester',text:'Missing candles <script>oops</script>',at:100,diagnostics:{},logLines:2},{id:'feature-1',kind:'feature',status:'discussing',name:'Tester',text:'New chart',at:200,diagnostics:{},logLines:0},{id:'fixed-1',kind:'bug',status:'fixed',name:'Tester',text:'Old bug',at:10,logLines:0}];
const calls=[];
const dom=new JSDOM(fs.readFileSync('public/admin.html','utf8'),{url:'https://hub.test/hub/admin',runScripts:'dangerously',virtualConsole:console,beforeParse(w){
 w.fetch=async(url,opts)=>{calls.push(String(url));const pathname=new URL(url,'https://hub.test').pathname;let body={ok:true};
 if(pathname.endsWith('/api/health'))body.version='test';
 if(pathname.endsWith('/api/feedback'))body.reports=reports;
 if(pathname.endsWith('/api/feedback/detail'))body.report={...reports[0],logs:[],diagnostics:{}};
 if(pathname.endsWith('/api/candles'))Object.assign(body,{enabled:true,venues:[{venue:'bybit',configured:true,health:{state:'running',lastSuccessAt:Date.now()},counts:{gapped:0,empty:0}}]});
 if(pathname.endsWith('/api/support'))Object.assign(body,{connected:true,budget:{limitMicros:50_000_000,usedMicros:12_000_000,reservedMicros:0,resetsAt:Date.UTC(2026,9,1),month:'2026-09'},items:[{id:'handoff',status:'human',question:'Help',messages:[{role:'assistant',text:'A human can help.'}]}],message:'Connected'});
 return {status:200,ok:true,json:async()=>body};};
 w.HTMLElement.prototype.scrollIntoView=()=>{};
}});
const w=dom.window,doc=w.document;const settle=()=>new Promise(r=>setTimeout(r,20));
await settle();assert.equal(errors.length,0,errors.join('\n'));
assert.equal(doc.querySelector('[data-hub-page-panel="overview"]').hidden,false);
assert.equal(calls.filter(x=>!x.endsWith('/api/health')).length,0,'no admin requests before sign in');
w.eval('token="test";loadHubPage("overview",true)');await settle();
assert.match(doc.getElementById('briefBugs').textContent,/Red · 1 open/);
assert.match(doc.getElementById('briefFeatures').textContent,/Amber · 1 open/);
assert.equal(doc.getElementById('briefCandles').textContent,'Green');
assert.match(doc.getElementById('briefSupport').textContent,/Red · 1 waiting/);
assert.match(doc.getElementById('supportBudgetSummary').textContent,/\$12.00 used.*\$50.00.*\$38.00 remaining/);
assert.equal(calls.some(x=>x.includes('billing')),false,'do not fetch settings on entry');
doc.querySelector('[data-hub-page="bugs"]').click();await settle();
assert.equal(doc.querySelector('[data-hub-page-panel="reports"]').hidden,false);
assert.equal(doc.querySelectorAll('#fbRows [data-report-id]').length,1);
const requestCount=calls.length;doc.getElementById('fbSearch').value='nothing';doc.getElementById('fbSearch').dispatchEvent(new w.Event('input'));await new Promise(r=>setTimeout(r,180));
assert.equal(calls.length,requestCount,'filters operate locally');assert.match(doc.getElementById('fbRows').textContent,/No reports match/);
doc.getElementById('fbSearch').value='';doc.querySelector('[data-hub-page="features"]').click();await settle();
assert.match(doc.getElementById('fbRows').textContent,/New chart/);assert.equal(doc.getElementById('fbRows').textContent.includes('Missing candles'),false);
doc.querySelector('[data-hub-page="overview"]').click();doc.querySelector('#briefBugList button').click();await settle();
assert.equal(doc.querySelector('.fbdetailrow').hidden,false);
assert.equal(doc.querySelector('#fbRows script'),null,'customer text escaped');
assert.equal(errors.length,0,errors.join('\n'));dom.window.close();
process.stdout.write('Admin workspace: default briefing, truthful counts, filters, safe text and report drilldown passed\n');
