import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {JSDOM,VirtualConsole} from 'jsdom';
import {freshHub,tmpDir} from './helpers.mjs';
const legacyFile=path.join(tmpDir('inbox-legacy'),'legacy.jsonl');
fs.writeFileSync(legacyFile,JSON.stringify({type:'escalate',id:'old-question',ts:1,question:'An earlier one-way question'})+'\n');
const h=await freshHub({support:{enabled:true,aiEnabled:false,apiKey:'',totalMonthlyMicros:50_000_000,legacyFile}});
let dom;
const until=async fn=>{for(let i=0;i<150;i++){if(fn())return;await new Promise(r=>setTimeout(r,20));}throw Error('UI action timed out');};
try {
 const baseHeaders={origin:'https://hub.test','x-wh-support':'1','content-type':'application/json'};
 const session=await fetch(h.origin+'/support/session',{method:'POST',headers:baseHeaders});
 const guestHeaders={...baseHeaders,cookie:session.headers.get('set-cookie').split(';')[0]};
 const chat=async body=>await(await fetch(h.origin+'/support/chat',{method:'POST',headers:guestHeaders,body:JSON.stringify(body)})).json();
 const created=await chat({text:'UI verification: can a human reply?',requestId:'inbox-ui-question',human:true});
 assert.equal(created.ok,true);const id=created.threads[0].id;
 const older=await chat({text:'Already answered question',requestId:'inbox-closed-question',human:true});
 const oldId=older.threads.find(t=>t.id!==id).id;
 await fetch(h.origin+'/admin/api/support',{method:'POST',headers:{'x-hub-admin':'test-admin-token','x-hub-csrf':'marketplace-config-v1','content-type':'application/json'},body:JSON.stringify({id:oldId,action:'resolve'})});
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
 dom=new JSDOM(fs.readFileSync('public/admin.html','utf8'),{url:h.origin+'/admin',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.fetch=(url,opts)=>fetch(new URL(url,h.origin),opts);w.HTMLElement.prototype.scrollIntoView=()=>{};}});
 const w=dom.window,doc=w.document;await w.eval('token="test-admin-token";showHubPage("support",true);supportRefresh()');
 const article=id=>doc.getElementById('support-'+id);
 const toggle=id=>article(id).querySelector('.support-open').click();
 const act=(id,action)=>article(id).querySelector(`[data-support-action="${action}"]`).click();
 assert.equal(doc.getElementById('supportFilter').value,'active');
 assert.equal(doc.querySelectorAll('#supportInbox article').length,1,'closed chats and legacy questions stay out of default inbox');
 assert.match(doc.getElementById('supportLegacyItems').textContent,/An earlier one-way question/);
 assert.match(doc.getElementById('briefSupport').textContent,/1 waiting/);
 assert.equal(article(id).querySelector('form'),null,'cards start compact');
 toggle(id);
 let input=article(id).querySelector('form textarea');assert.equal(input.closest('details'),null,'reply is visible when chat opens');
 input.value='Draft kept while collapsed';input.dispatchEvent(new w.Event('input'));toggle(id);toggle(id);
 assert.equal(article(id).querySelector('form textarea').value,'Draft kept while collapsed');
 input=article(id).querySelector('form textarea');input.value='Human UI verification reply <not markup>';
 article(id).querySelector('form').requestSubmit();
 await until(()=>doc.getElementById('supportReplyNotice').textContent.includes('Reply sent'));
 const received=await(await fetch(h.origin+'/support/chat',{headers:guestHeaders})).json();
 assert.equal(received.threads.find(t=>t.id===id).messages.at(-1).text,input.value);
 assert.equal(received.threads.find(t=>t.id===id).messages.at(-1).role,'human');
 assert.match(doc.getElementById('briefSupport').textContent,/no waiting replies/);
 assert.equal(doc.querySelector('#supportInbox not'),null,'reply content remains text');
 assert.equal(article(id).querySelector('textarea').value,'','successful send clears the saved draft');
 const realFetch=w.fetch;
 w.fetch=async (url,opts)=>{if(opts?.body&&JSON.parse(opts.body).action==='resolve')throw Error('Connection interrupted');return realFetch(url,opts);};
 act(id,'resolve');await until(()=>doc.getElementById('supportReplyNotice').textContent.includes('Connection interrupted'));
 assert.ok(article(id));assert.equal(article(id).querySelector('[data-support-action="resolve"]').disabled,false,'failed close stays open and retryable');
 w.fetch=realFetch;act(id,'resolve');await until(()=>!article(id));
 assert.match(doc.getElementById('supportReplyNotice').textContent,/Chat closed/);
 assert.match(doc.getElementById('supportInbox').textContent,/No open chats/);
 await w.eval('supportRefresh()');assert.equal(doc.querySelectorAll('#supportInbox article').length,0,'close survives a server refresh');
 doc.getElementById('supportFilter').value='resolved';doc.getElementById('supportFilter').dispatchEvent(new w.Event('change'));
 assert.equal(doc.querySelectorAll('#supportInbox article').length,2);
 toggle(id);assert.equal(article(id).querySelector('form'),null,'closed chat is read-only until reopened');
 assert.match(article(id).textContent,/Human UI verification reply/);
 act(id,'reopen');await until(()=>doc.getElementById('supportFilter').value==='active');
 assert.ok(article(id).querySelector('form'));assert.match(doc.getElementById('briefSupport').textContent,/1 waiting/);
 // A customer can also reopen a closed thread without losing its history.
 await chat({id:oldId,text:'I need another answer',requestId:'inbox-customer-reopen',human:true});await w.eval('supportRefresh()');
 assert.equal(doc.querySelectorAll('#supportInbox article').length,2);
 toggle(oldId);assert.equal(doc.querySelectorAll('#supportInbox .support-panel:not([hidden])').length,1,'only one chat expands at a time');
 assert.equal(article(id).querySelector('.support-open').getAttribute('aria-expanded'),'false');
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('Support inbox: compact rows, preserved drafts, real reply delivery, failed-close recovery, persistent close, closed history and both reopen paths verified');
} finally {dom?.window.close();await h.close();}
