import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {JSDOM,VirtualConsole} from 'jsdom';
import {freshHub,tmpDir} from './helpers.mjs';
const legacyFile=path.join(tmpDir('inbox-legacy'),'legacy.jsonl');
fs.writeFileSync(legacyFile,JSON.stringify({type:'escalate',id:'old-question',ts:1,question:'An earlier one-way question'})+'\n');
const h=await freshHub({support:{enabled:true,aiEnabled:false,apiKey:'',totalMonthlyMicros:50_000_000,legacyFile}});
let dom;
try {
 const baseHeaders={origin:'https://hub.test','x-wh-support':'1','content-type':'application/json'};
 const session=await fetch(h.origin+'/support/session',{method:'POST',headers:baseHeaders});
 const guestHeaders={...baseHeaders,cookie:session.headers.get('set-cookie').split(';')[0]};
 const created=await(await fetch(h.origin+'/support/chat',{method:'POST',headers:guestHeaders,body:JSON.stringify({text:'UI verification: can a human reply?',requestId:'inbox-ui-question',human:true})})).json();
 assert.equal(created.ok,true);const id=created.threads[0].id;
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
 dom=new JSDOM(fs.readFileSync('public/admin.html','utf8'),{url:h.origin+'/admin',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.fetch=(url,opts)=>fetch(new URL(url,h.origin),opts);w.HTMLElement.prototype.scrollIntoView=()=>{};}});
 const w=dom.window,doc=w.document;await w.eval('token="test-admin-token";showHubPage("support",true);supportRefresh()');
 assert.equal(doc.getElementById('supportFilter').value,'all');
 assert.equal(doc.querySelectorAll('#supportInbox article').length,1,'old one-way questions are separate');
 assert.match(doc.getElementById('supportLegacyItems').textContent,/An earlier one-way question/);
 assert.match(doc.getElementById('briefSupport').textContent,/1 waiting/,'legacy items do not inflate reply count');
 const article=doc.getElementById('support-'+id),form=article.querySelector('form'),input=form.querySelector('textarea');
 assert.equal(input.closest('details'),null,'reply composer is directly visible');
 input.value='Human UI verification reply <not markup>';
 form.requestSubmit();
 for(let i=0;i<100&&!doc.getElementById('supportReplyNotice').textContent;i++)await new Promise(r=>setTimeout(r,20));
 assert.match(doc.getElementById('supportReplyNotice').textContent,/Reply sent/);
 const received=await(await fetch(h.origin+'/support/chat',{headers:guestHeaders})).json();
 assert.equal(received.threads[0].messages.at(-1).text,input.value);
 assert.equal(received.threads[0].messages.at(-1).role,'human');
 assert.match(doc.getElementById('briefSupport').textContent,/no waiting replies/);
 assert.ok(doc.getElementById('support-'+id).querySelector('form'),'answered chat remains replyable in default view');
 assert.equal(doc.querySelector('#supportInbox not'),null,'reply content remains text');
 doc.getElementById('supportFilter').value='open';doc.getElementById('supportFilter').dispatchEvent(new w.Event('change'));
 assert.equal(doc.querySelectorAll('#supportInbox article').length,0);
 assert.match(doc.getElementById('supportInbox').textContent,/All chats|support inbox/);
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('Support inbox: visible composer, isolated legacy records, UI send and customer receipt verified');
} finally {dom?.window.close();await h.close();}
