import assert from 'node:assert/strict';
import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
import { SupportChat,SupportError } from '../dist/src/support-chat.js';
import { tmpDir,freshHub } from './helpers.mjs';
const cfg={enabled:true,aiEnabled:false,apiKey:'',totalMonthlyMicros:50_000_000};
const identity={owner:'owner',licenseId:'licensed',name:'Alice'};
const dir=tmpDir('support-chat');
const chat=new SupportChat(dir,cfg);
let d=await chat.message(identity,{text:'Help with installation',requestId:'request-0001',version:'0.90.128'});
const id=d.threads[0].id;
assert.equal(d.threads[0].status,'human');
assert.equal((await chat.message(identity,{text:'duplicate',requestId:'request-0001'})).threads[0].messages.length,1);
assert.throws(()=>chat.customer({...identity,owner:'intruder'},id),e=>e.status===404);
chat.action({id,action:'reply',text:'Open the guide',requestId:'reply-00001'});
chat.action({id,action:'reply',text:'Open the guide',requestId:'reply-00001'});
assert.equal(chat.customer(identity,id).threads[0].messages.length,2);
assert.equal(new SupportChat(dir,cfg).customer(identity,id).threads[0].messages[1].text,'Open the guide');
await chat.message(identity,{id,replyId:'reply-00001',action:'resolve'});assert.equal(chat.customer(identity,id).threads[0].status,'resolved');assert.equal(chat.customer(identity,id).threads[0].messages[1].feedback,'helpful');
await chat.message(identity,{id,replyId:'reply-00001',action:'human'});assert.equal(chat.admin().items.find(t=>t.id===id).waitingForHuman,true);assert.equal(chat.customer(identity,id).threads[0].messages[1].feedback,'needs_help');
await assert.rejects(chat.message({...identity,owner:'intruder'},{id,replyId:'reply-00001',action:'resolve'}),e=>e.status===404);

chat.action({id,action:'resolve'});
await chat.message(identity,{id,text:'One more question',requestId:'request-0002'});
assert.equal(chat.customer(identity,id).threads[0].status,'human');
chat.action({id,action:'knowledge',question:'How to begin?',answer:'Open the guide.'});
assert.equal(chat.admin().knowledge.length,1);
const originalUsage=chat.admin().spentMicros;chat.action({action:'budget',monthlyLimitUsd:75});assert.equal(chat.admin().budget.limitMicros,75_000_000);assert.equal(chat.admin().spentMicros,originalUsage);assert.equal(new SupportChat(dir,cfg).admin().budget.limitMicros,75_000_000);
assert.throws(()=>chat.action({action:'budget',monthlyLimitUsd:-1}),e=>e.status===400);
assert.throws(()=>chat.action({action:'budget',monthlyLimitUsd:'100'}),e=>e.status===400);
chat.action({action:'budget',monthlyLimitUsd:0});assert.equal(chat.allowance('owner').totalRemainingMicros,0);

let calls=0;
const provider=async()=>{calls++;return new Response(JSON.stringify({status:'completed',usage:{input_tokens:100,output_tokens:20},output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({answer:'Read the guide.',human:false})}]}]}));};
const ai=new SupportChat(tmpDir('support-ai'),{...cfg,aiEnabled:true,apiKey:'fake'},provider);
let aiThread;
for(let i=0;i<22;i++){const r=await ai.message(identity,{id:aiThread,text:'Question',requestId:'request-'+i});aiThread=r.threads[0].id;}
assert.equal(calls,20);assert.equal(ai.allowance('owner').dailyRemaining,0);
const bounded=new SupportChat(tmpDir('support-cap'),{...cfg,aiEnabled:true,apiKey:'fake',totalMonthlyMicros:7999},provider);
const before=calls;await bounded.message(identity,{text:'Help',requestId:'cap-request'});assert.equal(calls,before);
let finish;const inFlight=new SupportChat(tmpDir('support-flight'),{...cfg,aiEnabled:true,apiKey:'fake'},()=>new Promise(r=>{finish=r;}));
const run=inFlight.message(identity,{text:'Help',requestId:'first-request'});
await assert.rejects(inFlight.message(identity,{text:'Second',requestId:'second-request'}),e=>e.status===409);
const tid=inFlight.admin().items[0].id;assert.throws(()=>inFlight.action({id:tid,action:'delete'}),e=>e.status===409);inFlight.action({id:tid,action:'takeover'});finish(await provider());await run;
assert.equal(inFlight.customer(identity,tid).threads[0].messages.length,1);
assert.equal(inFlight.customer(identity,tid).threads[0].status,'human');
const failedDir=tmpDir('support-timeout');const failed=new SupportChat(failedDir,{...cfg,aiEnabled:true,apiKey:'fake'},async()=>{throw new Error('timeout');});
await failed.message(identity,{text:'Help',requestId:'failed-request'});
assert.equal(new SupportChat(failedDir,cfg).allowance('owner').userRemainingMicros,992000);
const h=await freshHub({support:cfg});
try{
 assert.equal((await fetch(h.origin+'/admin/api/support')).status,401);
 assert.equal((await fetch(h.origin+'/api/support/chat')).status,401);
 const auth={'x-hub-admin':'test-admin-token','content-type':'application/json'};
 assert.equal((await fetch(h.origin+'/admin/api/support',{method:'POST',headers:auth,body:'{}'})).status,403);
 const issue=await(await fetch(h.origin+'/admin/api/licenses',{method:'POST',headers:auth,body:JSON.stringify({name:'Customer',days:30})})).json();
 const res=await fetch(h.origin+'/api/support/chat',{method:'POST',headers:{'x-license':issue.token,'content-type':'application/json'},body:JSON.stringify({text:'Need help',requestId:'http-request'})});
 assert.equal(res.status,200);const result=await res.json();assert.equal(result.threads[0].status,'human');
 assert.equal(JSON.stringify(result).includes('apiKey'),false);
 const sessionHeaders={'x-wh-support':'1',origin:'https://hub.test'};
 assert.equal((await fetch(h.origin+'/support/session',{method:'POST'})).status,403);
 assert.equal((await fetch(h.origin+'/support/session',{method:'POST',headers:{...sessionHeaders,origin:'https://evil.test'}})).status,403);
 const session=await fetch(h.origin+'/support/session',{method:'POST',headers:sessionHeaders});assert.equal(session.status,200);
 const cookie=session.headers.get('set-cookie');assert.match(cookie,/HttpOnly; Secure; SameSite=Lax/);
 const guestHeaders={...sessionHeaders,cookie:cookie.split(';')[0],'content-type':'application/json'};
 assert.equal((await fetch(h.origin+'/support/chat')).status,401);
 const guest=await(await fetch(h.origin+'/support/chat',{method:'POST',headers:guestHeaders,body:JSON.stringify({text:'Website help',requestId:'website-request',version:'spoofed'})})).json();
 assert.equal(guest.threads[0].version,'website');assert.equal(guest.allowance.dailyRemaining,5);
 assert.equal((await fetch(h.origin+'/support/chat',{headers:{cookie:guestHeaders.cookie+'tampered'}})).status,401);
 assert.equal((await fetch(h.origin+'/api/support/chat?id='+guest.threads[0].id,{headers:{'x-license':issue.token}})).status,404);
 const inbox=await(await fetch(h.origin+'/admin/api/support',{headers:auth})).json();assert.equal(inbox.items.length,2);
 assert.equal((await fetch(h.origin+'/admin/api/support',{method:'POST',headers:{...auth,'x-hub-csrf':'marketplace-config-v1'},body:JSON.stringify({id:guest.threads[0].id,action:'reply',text:'Human website answer',requestId:'website-human-reply'})})).status,200);
 const reply=await(await fetch(h.origin+'/support/chat',{headers:guestHeaders})).json();assert.equal(reply.threads[0].messages.at(-1).text,'Human website answer');
}finally{await h.close();}
const grounded=new SupportChat(tmpDir('support-grounded'),{...cfg,aiEnabled:true,apiKey:'fake',knowledgeFile:fileURLToPath(new URL('../public/support-knowledge.json',import.meta.url))},async(url,init)=>{
 const payload=JSON.parse(init.body);assert.equal(payload.text.format.type,'json_schema');assert.equal(payload.text.format.strict,true);assert.match(payload.instructions,/Published September 2026 tutorial transcript/);assert.match(payload.instructions,/youtube\.com\/watch/);assert.ok(Buffer.byteLength(payload.instructions+JSON.stringify(payload.input))<=24000);return provider();
});
await grounded.message(identity,{text:'How does Hedge Bot minimum tranche coverage work?',requestId:'grounded-request',version:'0.90.129'});
assert.equal(grounded.customer(identity).threads[0].messages.at(-1).role,'assistant');
console.log('Support: durable delivery, ownership, idempotency, takeover, quotas, reservations and HTTP auth passed');

// Delete exactly one support conversation; preserve every other persisted field.
const other=await chat.message({...identity,owner:'other-owner',licenseId:'other-license'},{text:'Keep this conversation',requestId:'keep-request'});
const beforeDelete=JSON.parse(fs.readFileSync(dir+'/support-chat.v1.json','utf8'));
chat.action({id,action:'delete'});
const afterDelete=JSON.parse(fs.readFileSync(dir+'/support-chat.v1.json','utf8'));
assert.deepEqual(afterDelete,{...beforeDelete,threads:beforeDelete.threads.filter(t=>t.id!==id)});
assert.equal(new SupportChat(dir,cfg).customer(identity).threads.length,0);
assert.equal(chat.customer({...identity,owner:'other-owner'},other.threads[0].id).threads.length,1);
assert.throws(()=>chat.action({id,action:'delete'}),e=>e.status===404);
